// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/","redirect":"/dashboard","parentId":"2","id":"3"},"4":{"path":"/dashboard","parentId":"2","id":"4"},"5":{"path":"/users/list","parentId":"2","id":"5"},"6":{"path":"/orders/list","parentId":"2","id":"6"},"7":{"path":"/credits/manage","parentId":"2","id":"7"},"8":{"path":"/generations/list","parentId":"2","id":"8"},"9":{"path":"/templates/list","parentId":"2","id":"9"},"10":{"path":"/settings","parentId":"2","id":"10"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login" */'@/pages/Login.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__AppLayout" */'@/pages/AppLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Dashboard" */'@/pages/Dashboard.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Users__List" */'@/pages/Users/List.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Orders__List" */'@/pages/Orders/List.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Credits__Manage" */'@/pages/Credits/Manage.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Generations__List" */'@/pages/Generations/List.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Templates__List" */'@/pages/Templates/List.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Settings" */'@/pages/Settings.tsx')),
},
  };
}
